<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="RUN" Id="{bd49b256-e7ba-4b73-b669-380d1f428417}" SpecialFunc="None">
    <Declaration><![CDATA[(*
    This function runs all test suites that have been initialized.
*)
FUNCTION RUN]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_TcUnit.TcUnitRunner.RunTestSuiteTests();]]></ST>
    </Implementation>
    <LineIds Name="RUN">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>