<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="RUN_IN_SEQUENCE" Id="{a1bb30cd-f92f-4bab-aa26-6bd18db0fbc1}" SpecialFunc="None">
    <Declaration><![CDATA[(*
    This function runs all test suites that have been initialized.
    The test suites are run in sequence (one after the other).
*)
FUNCTION RUN_IN_SEQUENCE]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_TcUnit.TcUnitRunner.RunTestSuiteTestsInSequence(TimeBetweenTestSuitesExecution := GVL_Param_TcUnit.TimeBetweenTestSuitesExecution);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>