<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="RUN_IN_SEQUENCE" Id="{a1bb30cd-f92f-4bab-aa26-6bd18db0fbc1}" SpecialFunc="None">
    <Declaration><![CDATA[(*
    This function runs all test suites that have been initialized.
    The test suites are run in sequence (one after the other).
*)
FUNCTION RUN_IN_SEQUENCE
VAR_INPUT
	DelayTime	:TIME;		// Time between a Test-Suite is finished and the next Test-Suite starts
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_TcUnit.TcUnitRunner.RunTestSuiteTestsInSequence(DelayTime:=DelayTime);]]></ST>
    </Implementation>
    <LineIds Name="RUN_IN_SEQUENCE">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>