<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="PRG_TEST" Id="{35d0cb91-f449-41c5-be41-3ca0dfe074f2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
    PrimitiveTypesTest : FB_PrimitiveTypes_Test;
    AssertTrueFalse_Test : FB_AssertTrueFalse_Test;
    AssertEveryFailedTestTwice : FB_AssertEveryFailedTestTwice;
    CreateFourTestsWithSameName : FB_CreateFourTestsWithSameName;
    ArrayPrimitiveTypes_Test : FB_ArrayPrimitiveTypes_Test;
    CreateDisabledTest : FB_CreateDisabledTest;
    AnyPrimitiveTypes_Test : FB_AnyPrimitiveTypes_Test;
    AssertEveryFailedTestTwice_ArrayVersion : FB_AssertEveryFailedTestTwice_ArrayVersion;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>