<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_STRING" Id="{bad90aed-e2f4-4920-ad52-32ebaec9fc44}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_STRING
VAR_INPUT
    Ptr : POINTER TO STRING;
    Value : STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_STRING">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>