<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WRITE_PROTECTED_USINT" Id="{333ffbf6-74a7-432c-9a43-c67b08c23471}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_USINT
VAR_INPUT
    Ptr : POINTER TO USINT;
    Value : USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>