<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_TIME" Id="{fe63062b-7425-40a7-aecc-017a028de247}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_TIME
VAR_INPUT
    Ptr : POINTER TO TIME;
    Value : TIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>