<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WRITE_PROTECTED_DATE_AND_TIME" Id="{af0064cc-fa42-4eeb-9659-37d82d6b5671}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_DATE_AND_TIME
VAR_INPUT
    Ptr : POINTER TO DATE_AND_TIME;
    Value : DATE_AND_TIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>