<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WRITE_PROTECTED_UDINT" Id="{268b342f-fd80-4091-8fb8-f5f8dab7958d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_UDINT
VAR_INPUT
    Ptr : POINTER TO UDINT;
    Value : UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>