<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_PROTECTED_TIME_OF_DAY" Id="{c9020a0a-7555-43c0-b5e9-58aed910df89}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_TIME_OF_DAY : BOOL
VAR_INPUT
    ptr: POINTER TO TIME_OF_DAY;
    val: TIME_OF_DAY;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ptr^ := val;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_TIME_OF_DAY">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>