<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WRITE_PROTECTED_LREAL" Id="{339c1152-50eb-418b-b2b4-54330f145c79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_LREAL
VAR_INPUT
    Ptr : POINTER TO LREAL;
    Value : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>