<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_PROTECTED_DINT" Id="{e753c22d-5f40-4162-b951-1bab50066302}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_DINT : BOOL
VAR_INPUT
    ptr: POINTER TO DINT;
    val: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ptr^ := val;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_DINT">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>