<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_DATE" Id="{79d90978-55d9-4c8a-9385-a65057de0645}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_DATE
VAR_INPUT
    Ptr : POINTER TO DATE;
    Value : DATE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>