<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WRITE_PROTECTED_LWORD" Id="{c5f11757-2c55-43b4-9c4e-9a39fdf2cd53}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_LWORD
VAR_INPUT
    Ptr : POINTER TO LWORD;
    Value : LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>