<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_UINT" Id="{4b5114b2-1dc0-4e59-81df-bbfea3eeaaa0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_UINT
VAR_INPUT
    Ptr : POINTER TO UINT;
    Value : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>