<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_PROTECTED_DATE_AND_TIME" Id="{af0064cc-fa42-4eeb-9659-37d82d6b5671}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_DATE_AND_TIME : BOOL
VAR_INPUT
    ptr: POINTER TO DATE_AND_TIME;
    val: DATE_AND_TIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ptr^ := val;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_DATE_AND_TIME">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>