<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_PROTECTED_BOOL" Id="{d1649341-8878-4827-b4ef-c286e7025184}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_BOOL
VAR_INPUT
    Ptr : POINTER TO BOOL;
    Value : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_BOOL">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>