<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_BYTE" Id="{0bd58fcc-2342-4cd5-b054-08bdfb22baa1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_BYTE
VAR_INPUT
    Ptr : POINTER TO BYTE;
    Value : BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>