<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_SINT" Id="{e310eaa9-3123-4344-b07c-fc54b5c8e3ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_SINT
VAR_INPUT
    Ptr : POINTER TO SINT;
    Value : SINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>