<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="WRITE_PROTECTED_INT" Id="{d5d23a20-8f67-4a43-b9e4-bf7852dc7164}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_INT
VAR_INPUT
    Ptr : POINTER TO INT;
    Value : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>