<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_TEST" Id="{48f3a80c-6b31-445f-a938-08b4b352141e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
    PrimitiveTypes : FB_PrimitiveTypes;
    (* The FB_ExtendedTestInformation needs to be instantiated as the second test suite in order to get ID=1 as
       test suite identity, which is verified by the .NET-verifier *)
    ExtendedTestInformation : FB_ExtendedTestInformation;
    AssertTrueFalse : FB_AssertTrueFalse;
    AssertEveryFailedTestTwice : FB_AssertEveryFailedTestTwice;
    CreateFourTestsWithSameName : FB_CreateFourTestsWithSameName;
    ArrayPrimitiveTypes : FB_ArrayPrimitiveTypes;
    CreateDisabledTest : FB_CreateDisabledTest;
    AnyPrimitiveTypes : FB_AnyPrimitiveTypes;
    AssertEveryFailedTestTwiceArrayVersion : FB_AssertEveryFailedTestTwiceArrayVersion;
    AnyToUnionValue : FB_AnyToUnionValue;
    MultipleAssertWithSameParametersInSameCycleWithSameTest : FB_MultipleAssertWithSameParametersInSameCycleWithSameTest;
    MultipleAssertWithSameParametersInDifferentCyclesButWithDifferentTests : FB_MultipleAssertWithSameParametersInDifferentCyclesButWithDifferentTests;
    MultipleAssertWithSameParametersInDifferentCyclesAndInSameTest : FB_MultipleAssertWithSameParametersInDifferentCyclesAndInSameTest;
    SkipAssertionsWhenFinished : FB_SkipAssertionsWhenFinished;
    AdjustAssertFailureMessageToMax253CharLengthTest : FB_AdjustAssertFailureMessageToMax253CharLengthTest;
    EmptyTestSuite : FB_EmptyTestSuite;
    CheckIfSpecificTestIsFinished : FB_CheckIfSpecificTestIsFinished;
    WriteProtectedFunctions : FB_WriteProtectedFunctions;
    TestNumberOfAssertionsCalculation : FB_TestNumberOfAssertionsCalculation;
    TestFileControl : FB_TestFileControl;
    TestXmlControl : FB_TestXmlControl;
    TestStreamBuffer : FB_TestStreamBuffer;
    TestFinishedNamed : FB_TestFinishedNamed;
    EmptyAssertionMessage : FB_EmptyAssertionMessage;
    AssertCountExceedsMaxNumber : FB_AssertCountExceedsMaxNumber;

    (* The testsuite below is not active, as it will make TcUnit to abort. Uncomment if you want
       to test the function of where a test with a name that doesn't exist is set to finished *)
    //TestFinishedNamedDoesNotExist : FB_TestFinishedNamedDoesNotExist;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* There are two ways to run TcUnit test suites:
    1. The RUN() will run all the test suites in parallel
    2. The RUN_IN_SEQUENCE() will run the test suites in sequence (one-by-one, next one doesn't start until the previous one is finished)
    Only use one of them at a time
*)

TcUnit.RUN();
//TcUnit.RUN_IN_SEQUENCE(T#0MS);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>