<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_ANY_STRING" Id="{bad90aed-e2f4-4920-ad52-32ebaec9fc44}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_ANY_STRING : BOOL
VAR_INPUT
    ptr: POINTER TO STRING;
    val: STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ptr^ := val;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_ANY_STRING">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>