<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="WRITE_ANY_UDINT" Id="{268b342f-fd80-4091-8fb8-f5f8dab7958d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_ANY_UDINT : BOOL
VAR_INPUT
    ptr: POINTER TO UDINT;
    val: UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ptr^ := val;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_ANY_UDINT">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>